services:
  api:
    image: loicfaugieres/cliandcollect-api
    container_name: cliandcollect-api
    ports:
      - "80:8080"
      - "8080:8080"
    env_file:
      - ./.env
    networks:
      - cliandcollect-network

networks:
  cliandcollect-network:
    name : cliandcollect-network